# Generated by Django 4.2.1 on 2023-06-13 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='message',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='name',
            new_name='username',
        ),
    ]
